# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit treeSS.Rmd to modify this file

## ----setup, include = FALSE------------------------------------
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.width = 7,
  fig.height = 4.5,
  out.width = "90%",
  cache = TRUE,
  cache.lazy = FALSE
)

# Narrow the console width for printed output. The R Journal's
# two-column PDF layout truncates verbatim lines longer than ~70
# characters; 65 leaves a safety margin and matches what the
# `treeSS` print methods use when wrapping their own long fields
# (Leaf IDs, Regions).
options(width = 65)

# Belt-and-braces: install a knitr output hook that hard-wraps any
# console output line longer than 65 characters before it reaches
# pdflatex. This is independent of how the underlying R function
# chose to print its output -- so even if a function returns a
# single very long line via cat() or print(), it still gets wrapped
# in the PDF.
local({
  default_output_hook <- knitr::knit_hooks$get("output")
  wrap_one_line <- function(line) {
    if (nchar(line) <= 65L) return(line)
    # Preserve any leading "#> " that knitr added (per the `comment`
    # chunk option) and apply it to continuation lines as well.
    prefix_match <- regmatches(line, regexpr("^#>\\s*", line))
    prefix <- if (length(prefix_match)) prefix_match else ""
    body   <- substr(line, nchar(prefix) + 1L, nchar(line))
    wraps  <- strwrap(body, width = max(20L, 65L - nchar(prefix)),
                      exdent = 2L)
    paste0(prefix, wraps, collapse = "\n")
  }
  knitr::knit_hooks$set(output = function(x, options) {
    # `x` is a single character string of the chunk's stdout, with
    # newlines embedded. Split, wrap each line, recombine.
    lines <- unlist(strsplit(x, "\n", fixed = TRUE))
    wrapped <- vapply(lines, wrap_one_line, character(1L))
    default_output_hook(paste(wrapped, collapse = "\n"), options)
  })
})

# A single global seed at the top of the document makes the entire paper
# reproducible end-to-end, but every Monte Carlo invocation also passes its
# own `seed = ...` argument so reviewers can rerun any individual chunk.
set.seed(2016)

# ggplot2 is loaded here so that the helper below can be defined at setup
# time. Subsequent chunks reload it explicitly to keep them runnable in
# isolation by reviewers who pick a single chunk to inspect.
suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(sf)
})


## ----functions, echo = FALSE-----------------------------------
funs <- data.frame(
  Function = c("treespatial_scan()", "circular_scan()", "tree_scan()",
               "iterative_scan()", "filter_clusters()",
               "get_cluster_regions()", "aggregate_tree()",
               "build_zones()"),
  Purpose = c(
    "Tree-spatial scan; main entry point",
    "Kulldorff's circular spatial scan, no tree",
    "Tree-based scan, no spatial dimension",
    "Sequential conditional scan with Holm--Bonferroni correction",
    "Distinct secondary clusters per Cançado et al. (2025), Sec. 5.1.1",
    "Tidy region-by-cluster table for plotting",
    "Roll counts up the tree to internal nodes",
    "Construct the family of circular zones"
  )
)
knitr::kable(
  funs, booktabs = TRUE,
  caption = "User-facing functions in the treeSS package."
)


## ----datasets, echo = FALSE------------------------------------
ds <- data.frame(
  Dataset = c("rj_mortality", "chicago_crimes", "london_collisions"),
  Country = c("Brazil", "USA", "UK"),
  Domain  = c("Health", "Crime", "Road safety"),
  Regions = c("89", "77", "33"),
  `Tree (nodes)` = c("ICD-10 (622)",
                     "Crime taxonomy (2841)",
                     "Conditions (81)"),
  check.names = FALSE
)
knitr::kable(
  ds, booktabs = TRUE,
  caption = "Real-world datasets shipped with treeSS. The regions column reports the number of spatial units. Each dataset is paired with a corresponding tree object."
)


## ----rj-load---------------------------------------------------
library(treeSS)
data(rj_mortality)
data(rj_tree)

c(rows = nrow(rj_mortality),
  municipalities = length(unique(rj_mortality$region_id)),
  tree_nodes = nrow(rj_tree),
  total_deaths = sum(rj_mortality$cases),
  total_births = sum(unique(rj_mortality[, c("region_id", "live_births")])$live_births))


## ----rj-scan, cache = TRUE-------------------------------------
result_rj <- treespatial_scan(
  cases       = rj_mortality$cases,
  population  = rj_mortality$live_births,
  region_id   = rj_mortality$region_id,
  x           = rj_mortality$x,
  y           = rj_mortality$y,
  node_id     = rj_mortality$node_id,
  tree        = rj_tree,
  max_pop_pct = 0.50,
  nsim        = 999, seed = 2016, n_cores = 4L
)
print(result_rj)


## ----rj-spatial-only, cache = TRUE-----------------------------
# Aggregate cases to one row per municipality.
rj_agg <- unique(rj_mortality[, c("region_id", "x", "y", "live_births")])
rj_agg$cases <- tapply(rj_mortality$cases,
                       rj_mortality$region_id,
                       sum)[as.character(rj_agg$region_id)]
rj_agg <- rj_agg[order(rj_agg$region_id), ]

result_rj_spatial <- circular_scan(
  cases       = rj_agg$cases,
  population  = rj_agg$live_births,
  region_id   = rj_agg$region_id,
  x           = rj_agg$x,
  y           = rj_agg$y,
  max_pop_pct = 0.50,
  nsim        = 999, seed = 2016, n_cores = 4L
)
result_rj_spatial$most_likely_cluster$region_ids


## ----rj-filter-------------------------------------------------
fc <- filter_clusters(result_rj)
head(fc[, c("node_id", "n_regions", "cases", "expected", "llr", "pvalue")], 5)


## ----rj-map-data, message = FALSE------------------------------
library(ggplot2)
library(geobr)
library(sf)
library(dplyr)

rj_map <- read_municipality(code_muni = "RJ", year = 2016,
                            showProgress = FALSE)
rj_map$code6 <- as.integer(substr(rj_map$code_muni, 1, 6))
ibge_lookup <- unique(rj_mortality[, c("region_id", "ibge_code")])


## ----rj-plot-primary, fig.cap = "Most likely tree-spatial cluster in Rio de Janeiro: 18 contiguous municipalities (red) of the north fluminense region with elevated mortality from ICD-10 P209 (unspecified intrauterine hypoxia). LR = 38.83, p < 0.001, 27 deaths observed against 3.34 expected.", fig.width = 7, fig.height = 5----
mlc_rj <- result_rj$most_likely_cluster
cr_rj_1 <- merge(
  get_cluster_regions(result_rj, n_clusters = 1L, overlap = FALSE),
  ibge_lookup, by = "region_id"
)

# Join cluster-membership data into the polygon layer. We use the
# sf-aware `dplyr::left_join.sf` method directly, which preserves
# geometry across rows even when the right-hand-side data.frame has
# duplicate join keys (as it does for cr_rj_2 below, which has 2 rows
# per region under overlap = TRUE). This is the pattern used in the
# official `geobr` vignette.
rj_p1 <- left_join(rj_map, cr_rj_1, by = c("code6" = "ibge_code"))

ggplot(rj_p1) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.15, alpha = 0.80) +
  scale_fill_manual(
    values   = c("1" = "#C44E52"), na.value = "gray95",
    na.translate = FALSE,
    labels   = paste0(mlc_rj$node_id, " (",
                      length(mlc_rj$region_ids), " municipalities)"),
    name     = "Cluster"
  ) +
  labs(subtitle = sprintf("LR = %.1f, p = %s | %d deaths (expected %.1f)",
                          mlc_rj$llr,
                          format.pval(result_rj$pvalue, digits = 3),
                          mlc_rj$cases, mlc_rj$expected)) +
  theme_minimal(base_size = 13) +
  theme(plot.subtitle = element_text(color = "gray35", size = 11),
        axis.title    = element_blank(),
        axis.text     = element_text(color = "gray55", size = 9))


## ----rj-plot-top2, fig.cap = "Top-2 distinct tree-spatial clusters in Rio de Janeiro per Cançado et al. (2025), Section 5.1.1: the primary cluster (P209, north fluminense) and the highest-LR distinct secondary cluster.", fig.width = 9, fig.height = 5----
cr_rj_2 <- merge(
  get_cluster_regions(result_rj, n_clusters = 2L, overlap = TRUE),
  ibge_lookup, by = "region_id"
)

rj_p2 <- left_join(rj_map, cr_rj_2, by = c("code6" = "ibge_code"))

ggplot(rj_p2[!is.na(rj_p2$panel), ]) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.12, alpha = 0.80) +
  scale_fill_manual(values = c("1" = "#C44E52", "2" = "#4C72B0"),
                    na.value = "gray95", na.translate = FALSE) +
  facet_wrap(~ panel, nrow = 1L) +
  theme_minimal(base_size = 12) +
  theme(strip.text = element_text(face = "bold", size = 11),
        axis.title = element_blank(),
        axis.text  = element_text(color = "gray55", size = 9),
        legend.position = "none")


## ----chi-scan, cache = TRUE------------------------------------
data(chicago_crimes)
data(chicago_tree)
data(chicago_map)

result_chi <- treespatial_scan(
  cases       = chicago_crimes$cases,
  population  = chicago_crimes$pop_residential,
  region_id   = chicago_crimes$region_id,
  x           = chicago_crimes$x,
  y           = chicago_crimes$y,
  node_id     = chicago_crimes$node_id,
  tree        = chicago_tree,
  max_pop_pct = 0.25,
  nsim        = 999, seed = 2023, n_cores = 4L
)
print(result_chi)


## ----chi-plot-primary, fig.cap = "Most likely tree-spatial cluster in Chicago, 2023: contiguous community areas on the South Side with elevated crime incidence. Denominator: residential population (ACS 2020 5-year).", fig.width = 6.5, fig.height = 6.5----
mlc_chi <- result_chi$most_likely_cluster
chi_lookup <- unique(chicago_crimes[, c("region_id", "area_number")])
cr_chi_1 <- merge(
  get_cluster_regions(result_chi, n_clusters = 1L, overlap = FALSE),
  chi_lookup, by = "region_id"
)
chi_p1 <- left_join(chicago_map, cr_chi_1,
                    by = c("AREA_NUM" = "area_number"))

ggplot(chi_p1) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.15, alpha = 0.80) +
  scale_fill_manual(
    values   = c("1" = "#C44E52"), na.value = "gray95",
    na.translate = FALSE,
    labels   = paste0(mlc_chi$node_id, " (",
                      length(mlc_chi$region_ids), " areas)"),
    name     = "Cluster"
  ) +
  labs(subtitle = sprintf("LR = %.1f, p = %s | %d incidents (expected %.1f)",
                          mlc_chi$llr,
                          format.pval(result_chi$pvalue, digits = 3),
                          mlc_chi$cases, mlc_chi$expected)) +
  theme_minimal(base_size = 13) +
  theme(plot.subtitle = element_text(color = "gray35", size = 11),
        axis.title    = element_blank(),
        axis.text     = element_text(color = "gray55", size = 9))


## ----chi-plot-top2, fig.cap = "Top-2 distinct tree-spatial clusters in Chicago per Cançado et al. (2025), Section 5.1.1: primary cluster (left) and the highest-LR distinct secondary cluster (right).", fig.width = 9, fig.height = 5----
cr_chi_2 <- merge(
  get_cluster_regions(result_chi, n_clusters = 2L, overlap = TRUE),
  chi_lookup, by = "region_id"
)
chi_p2 <- left_join(chicago_map, cr_chi_2,
                    by = c("AREA_NUM" = "area_number"))

ggplot(chi_p2[!is.na(chi_p2$panel), ]) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.12, alpha = 0.80) +
  scale_fill_manual(values = c("1" = "#C44E52", "2" = "#4C72B0"),
                    na.value = "gray95", na.translate = FALSE) +
  facet_wrap(~ panel, nrow = 1L) +
  theme_minimal(base_size = 12) +
  theme(strip.text = element_text(face = "bold", size = 11),
        axis.title = element_blank(),
        axis.text  = element_text(color = "gray55", size = 9),
        legend.position = "none")


## ----ldn-scan, cache = TRUE------------------------------------
data(london_collisions)
data(london_tree)
data(london_boroughs_map)

result_ldn <- treespatial_scan(
  cases       = london_collisions$cases,
  population  = london_collisions$population,
  region_id   = london_collisions$region_id,
  x           = london_collisions$x,
  y           = london_collisions$y,
  node_id     = london_collisions$node_id,
  tree        = london_tree,
  max_pop_pct = 0.40,
  nsim        = 999, seed = 2022, n_cores = 4L,
  model       = "poisson"
)
print(result_ldn)


## ----ldn-plot-primary, fig.cap = "Most likely tree-spatial cluster in London road collisions, 2022.", fig.width = 7, fig.height = 5----
mlc_ldn <- result_ldn$most_likely_cluster
ldn_lookup <- unique(london_collisions[, c("region_id", "borough")])
cr_ldn_1 <- merge(
  get_cluster_regions(result_ldn, n_clusters = 1L, overlap = FALSE),
  ldn_lookup, by = "region_id"
)
ldn_p1 <- left_join(london_boroughs_map, cr_ldn_1,
                    by = c("NAME" = "borough"))

ggplot(ldn_p1) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.15, alpha = 0.80) +
  scale_fill_manual(
    values   = c("1" = "#C44E52"), na.value = "gray95",
    na.translate = FALSE,
    labels   = paste0(mlc_ldn$node_id, " (",
                      length(mlc_ldn$region_ids), " boroughs)"),
    name     = "Cluster"
  ) +
  labs(subtitle = sprintf("LR = %.1f, p = %s | %d collisions (expected %.1f)",
                          mlc_ldn$llr,
                          format.pval(result_ldn$pvalue, digits = 3),
                          mlc_ldn$cases, mlc_ldn$expected)) +
  theme_minimal(base_size = 13) +
  theme(plot.subtitle = element_text(color = "gray35", size = 11),
        axis.title    = element_blank(),
        axis.text     = element_text(color = "gray55", size = 9))


## ----ldn-plot-top2, fig.cap = "Top-2 distinct tree-spatial clusters in London per Cançado et al. (2025), Section 5.1.1: primary cluster (left) and the highest-LR distinct secondary cluster (right).", fig.width = 9, fig.height = 5----
cr_ldn_2 <- merge(
  get_cluster_regions(result_ldn, n_clusters = 2L, overlap = TRUE),
  ldn_lookup, by = "region_id"
)
ldn_p2 <- left_join(london_boroughs_map, cr_ldn_2,
                    by = c("NAME" = "borough"))

ggplot(ldn_p2[!is.na(ldn_p2$panel), ]) +
  geom_sf(aes(fill = factor(cluster)), color = "gray40",
          linewidth = 0.12, alpha = 0.80) +
  scale_fill_manual(values = c("1" = "#C44E52", "2" = "#4C72B0"),
                    na.value = "gray95", na.translate = FALSE) +
  facet_wrap(~ panel, nrow = 1L,
             labeller = labeller(panel = function(x) {
               vapply(x, function(s) {
                 parts <- strsplit(s, "\n", fixed = TRUE)[[1]]
                 wrapped <- vapply(parts, function(p)
                   paste(strwrap(p, width = 32), collapse = "\n"),
                   character(1L))
                 paste(wrapped, collapse = "\n")
               }, character(1L))
             })) +
  theme_minimal(base_size = 12) +
  theme(strip.text = element_text(face = "bold", size = 10),
        axis.title = element_blank(),
        axis.text  = element_text(color = "gray55", size = 9),
        legend.position = "none")


## ----ldn-iter, cache = TRUE------------------------------------
iter_ldn <- iterative_scan(
  cases       = london_collisions$cases,
  population  = london_collisions$population,
  region_id   = london_collisions$region_id,
  x           = london_collisions$x,
  y           = london_collisions$y,
  node_id     = london_collisions$node_id,
  tree        = london_tree,
  max_pop_pct = 0.40,
  max_iter    = 4L, alpha = 0.05,
  nsim        = 999, seed = 2022, n_cores = 4L,
  verbose     = FALSE
)
print(iter_ldn)


## ----ldn-plot-iter, fig.cap = "Iterative scan on London collisions: each cluster is detected after conditioning the data on those previously detected, with Holm--Bonferroni correction across iterations.", fig.width = 9, fig.height = 9----
n_iter <- iter_ldn$n_iter
if (n_iter > 0) {
  cr_iter <- merge(
    get_cluster_regions(iter_ldn, n_clusters = n_iter, overlap = TRUE),
    ldn_lookup, by = "region_id"
  )
  ldn_iter_p <- left_join(london_boroughs_map, cr_iter,
                          by = c("NAME" = "borough"))
  pal_iter <- c("#C44E52", "#4C72B0", "#55A868",
                "#8172B2")[seq_len(n_iter)]
  names(pal_iter) <- as.character(seq_len(n_iter))

  ldn_iter_p <- left_join(london_boroughs_map, cr_iter,
                          by = c("NAME" = "borough"))
  pal_iter <- c("#C44E52", "#4C72B0", "#55A868",
                "#8172B2")[seq_len(n_iter)]
  names(pal_iter) <- as.character(seq_len(n_iter))

  ggplot(ldn_iter_p[!is.na(ldn_iter_p$panel), ]) +
    geom_sf(aes(fill = factor(cluster)), color = "gray40",
            linewidth = 0.12, alpha = 0.80) +
    scale_fill_manual(values = pal_iter,
                      na.value = "gray95", na.translate = FALSE) +
    facet_wrap(~ panel, nrow = 2L,
               labeller = labeller(panel = function(x) {
                 vapply(x, function(s) {
                   parts <- strsplit(s, "\n", fixed = TRUE)[[1]]
                   wrapped <- vapply(parts, function(p)
                     paste(strwrap(p, width = 38), collapse = "\n"),
                     character(1L))
                   paste(wrapped, collapse = "\n")
                 }, character(1L))
               })) +
    theme_minimal(base_size = 12) +
    theme(strip.text = element_text(face = "bold", size = 10),
          axis.title = element_blank(),
          axis.text  = element_text(color = "gray55", size = 9),
          legend.position = "none")
} else {
  message("Iterative scan returned no significant clusters at alpha = 0.05.")
}


## ----bench, echo = FALSE---------------------------------------
bench <- data.frame(
  Dataset       = c("rj_mortality", "chicago_crimes", "london_collisions"),
  Regions       = c(89, 77, 33),
  `Tree nodes`  = c(622, 2841, 81),
  `Serial (s)`  = c("~120", "~480", "~5"),
  `4 threads (s)` = c("~30", "~110", "~2"),
  Speedup       = c("~4x", "~4-5x", "~2-3x"),
  check.names = FALSE
)
knitr::kable(
  bench, booktabs = TRUE,
  caption = "Indicative wall-clock times for nsim = 999. London is small enough that thread-startup overhead dominates."
)


## ----related, echo = FALSE-------------------------------------
rel <- data.frame(
  Tool = c("treeSS",
           "scanstatistics",
           "rsatscan",
           "SpatialEpi",
           "SaTScan",
           "TreeScan"),
  `Scan type` = c("tree-spatial, tree, circular",
                  "space-time anomaly detection",
                  "inherits from SaTScan",
                  "circular Kulldorff",
                  "circular, elliptic, space-time",
                  "tree-only, tree-time"),
  Implementation = c("R + C++ (Rcpp, OpenMP)",
                     "R",
                     "R wrapper around binary",
                     "R",
                     "C++ standalone",
                     "C++ standalone"),
  `On CRAN`  = c("yes (this paper)",
                 "yes",
                 "yes",
                 "yes",
                 "no",
                 "no"),
  check.names = FALSE
)
knitr::kable(
  rel, booktabs = TRUE,
  caption = "treeSS in the landscape of scan-statistic software."
)


## ----session-info, echo = FALSE, eval = FALSE------------------
#> sessionInfo()

